<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>30baaab0-65b1-4a3e-a2e3-15c7336a0723</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="NLog.Web.AspNetCore" Version="5.4.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AuthCore.Application\AuthCore.Application.csproj" />
		<ProjectReference Include="..\AuthCore.Domain\AuthCore.Domain.csproj" />
		<ProjectReference Include="..\AuthCore.Infrastructure\AuthCore.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="wwwroot\swagger\SwaggerStyle.css" />
		<None Include="nlog.config" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
